### ISSUE TITLE
Links in /docs/user_guide/ep_in_python.ipynb are dead

### ISSUE THREAD

**Issue by keesmulder** [avast/ep-stats#30]
The links to pages such as 'Principles' are dead. They refer to .html files, but the folder only has Markdown files. Would do a PR, but I don't know if the solution should be either:
- Add the html files converted from the markdown files to the repo, or
- Change links to refer to the .md files.

**Comment by jancervenka** [comment]
Hi! The links are designed to work when the documentation is built and deployed. [Your example](https://avast.github.io/ep-stats/user_guide/ep_in_python.html). They don't work in the original source files because the `.md` files are converted to `.html` during the build process.
